coms309::Users::Users
int coms309.Users.Users.id
String coms309.Users.Users.first_name
String coms309.Users.Users.last_name
String coms309.Users.Users.email
String coms309.Users.Users.password
permission coms309.Users.Users.role
Set<GamePost> coms309.Users.Users.createdGamePosts
Set<SkillLevel> coms309.Users.Users.skill_levels
Set<GamePost> coms309.Users.Users.gamePost
public coms309.Users.Users::Users()
Default constructor.
Arie 10/20/2023
Referenced by coms309.Users.Users.equals.
public coms309.Users.Users::Users(String firstName, String last_name, String email, String password)
Constructor.
Arie 10/20/2023 firstName The person's first name. last_name The person's last name. email The email. password The password.
public int coms309.Users.Users::getId()
Gets the identifier.
Arie 10/20/2023 int.
public void coms309.Users.Users::setId(int id)
Sets an identifier.
Arie 10/20/2023 id .
public String coms309.Users.Users::getFirst_name()
Get the first name.
Arie 10/20/2023 String.
public void coms309.Users.Users::setFirst_name(String firstName)
Set the first name.
Arie 10/20/2023 firstName .
public String coms309.Users.Users::getLast_name()
Get the last name.
Arie 10/20/2023 String.
public void coms309.Users.Users::setLast_name(String lastName)
Set the last name.
Arie 10/20/2023 lastName .
public String coms309.Users.Users::getEmail()
Gets the email.
Arie 10/20/2023 The email.
public void coms309.Users.Users::setEmail(String email)
Sets an email.
Arie 10/20/2023 email The email.
public String coms309.Users.Users::getPassword()
Gets the password.
Arie 10/20/2023 The password.
public void coms309.Users.Users::setPassword(String password)
Sets a password.
Arie 10/20/2023 password The password.
public Set< GamePost > coms309.Users.Users::getGamePost()
Gets game post.
Arie 10/20/2023 The game post.
public void coms309.Users.Users::setGamePost(Set< GamePost > gamePost)
Sets game post.
Arie 10/20/2023 gamePost The game post.
public Set< GamePost > coms309.Users.Users::getCreatedGamePosts()
Gets created game posts.
Arie 10/20/2023 The created game posts.
public void coms309.Users.Users::setCreatedGamePosts(Set< GamePost > createdGamePosts)
Sets created game posts.
Arie 10/20/2023 createdGamePosts The created game posts.
public Set< SkillLevel > coms309.Users.Users::getSkill_levels()
Gets skill levels.
Arie 10/20/2023 The skill levels.
public void coms309.Users.Users::setSkill_levels(Set< SkillLevel > sports_skill_levels)
Sets skill levels.
Arie 10/20/2023 sports_skill_levels The sports skill levels.
public boolean coms309.Users.Users::isAuthenticated(String email, String password)
Query if 'email' is authenticated.
Arie 10/20/2023 email The email. password The password. True if authenticated, false if not.
public boolean coms309.Users.Users::isAdmin(Users u)
Query if 'u' is admin.
Arie 10/20/2023 u The Users to process. True if admin, false if not.
public permission coms309.Users.Users::getRole()
Gets the role.
Arie 10/20/2023 The role.
Referenced by coms309.Users.UserController.getUserRole.
public void coms309.Users.Users::setRole(permission role)
Sets a role.
Arie 10/20/2023 role The role.
Override public boolean coms309.Users.Users::equals(Object o)
Tests if this Object is considered equal to another.
Arie 10/20/2023 o The object to compare to this object. True if the objects are considered equal, false if they are not.
References coms309.Users.Users.equals, coms309.Users.Users.Users.
Referenced by coms309.Users.Users.equals.
public Flux< String > coms309.Users.Users::getUserStream()
Gets user stream.
Arie 10/20/2023 The user stream.